site_title = "MyArxiv"
limit_days = 3
cache_url = "https://starslabs.github.io/daily_arxiv/cache.json"

[[sources]]
limit = 100
category = "cs.CL"
title = "Computation and Language"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
